### PR TITLE
rimage: make ace15 signing to use cavs25 functions

### PR DESCRIPTION
**Pull request by juimonen**
Ace signing is currently missing openssl3 support, so add it

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Comment by juimonen** [comment]
let's see if this works...

**Comment by aiChaoSONG** [comment]
The build and signing work with this patch on Ubuntu22.04, but I don't have debug key to verify this patch on MTL RVP, let's wait for a while.

**Review by aiChaoSONG — APPROVED** [review]
Verified on MTL nocodec RVP, firmware is compiled with my Ubuntu2204

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@juimonen will need a west update now.

**Pull request merged**
