### PR TITLE
README.md: explain how to run SOF tests on rimage work in progress

### PR DESCRIPTION
**Pull request by marc-hb**
Signed-off-by: Marc Herbert <marc.herbert@intel.com>

### CODE REVIEW

**Comment by marc-hb** [comment]
Thoroughly tested (must eat my own dog food) with https://github.com/thesofproject/sof/pull/4776 and https://github.com/thesofproject/sof/pull/4778

The inability of some CIs to report build failures was very instructive.

**Comment by marc-hb** [comment]
To look at the formatted and prettier output go to Commits -> and <> brackets. For the first version this goes to https://github.com/marc-hb/rimage/tree/fa388bd68238

**Review by lgirdwood — APPROVED** [review]
Thanks @marc-hb looks good, Will be helpful with testing PRs.

**Comment by marc-hb** [comment]
This Github feature can also be used to pretend that Linus Torvalds invented Bitcoin - or any other fake news of your choice: https://lwn.net/Articles/884105/

**Pull request merged**
