### PR TITLE
config: tgl-cavs: add iir and fir eq module config

### PR DESCRIPTION
**Pull request by juimonen**
This patch adds module config iir eq module.

Signed-off-by: Jaska Uimonen <jaska.uimonen@intel.com>

### CODE REVIEW

**Review by singalsu — APPROVED** [review]

**Review by lgirdwood — COMMENTED** [review]
LGTM

**Review by singalsu — APPROVED** [review]

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@juimonen still draft ?

**Comment by juimonen** [comment]
@lgirdwood we are working with @singalsu to get the eqs up and running. I'll move all related PR's from draft when we get eq working.

**Comment by juimonen** [comment]
@lgirdwood no more draft. I see we have not same modules in tgl-h than in tgl conf... @aiChaoSONG I think smart amp etc should be there also? I can then update eqs also

**Comment by juimonen** [comment]
aah sorry my bad, so I guess the modules are only in tgl-cavs, not in tgl or tgl-h. So this should be good to go.

**Pull request merged**
