### PR TITLE
TEST: mtl: Use DP scheduler for AEC module

### PR DESCRIPTION
**Pull request by yongzhi1**
Change domain_types to DP, and allow it to run all 3 cores.

### CODE REVIEW

**Review by RanderWang — APPROVED** [review]

**Comment by marcinszkudlinski** [comment]
rimage repo has been moved to sof https://github.com/thesofproject/sof/pull/8297/

@lgirdwood, is old rimage obsolete now?

the change itself looks good

**Review by marcinszkudlinski — APPROVED** [review]
looks good, just wait with merge till DP is ready for AEC

**Comment by marcinszkudlinski** [comment]
btw. rimage has been

**Comment by marcinszkudlinski** [comment]
rimage repo is obsolete
https://github.com/thesofproject/sof/pull/8297/
pls merge to sof main

**Comment by lgirdwood** [comment]
@marcinszkudlinski does this need to merge in this repo for mtl-06 branch ? Or good for @yongzhi1 to close and merge into mtl-07 ?

**Comment by marcinszkudlinski** [comment]
I prefer to main/007. There were a lot of changes since 006 branch, including "sparse cache" removal. 
Merge all and AEC changes to 006 would be very problematic.

**Comment by yongzhi1** [comment]
Thanks for the quick reviews, will close and push to sof main since the rimage repo is obsolete now.

**Pull request closed without merging**
