### PR TITLE
mtl: remove smart amp config in basefw

### PR DESCRIPTION
**Pull request by RanderWang**
Smart amp will be a loadable module.

### CODE REVIEW

**Comment by RanderWang** [comment]
@kv2019i is this branch correct ? thanks!

**Review by kv2019i — APPROVED** [review]

**Comment by lgirdwood** [comment]
@RanderWang @kv2019i should we be pushing PRs here now that @marc-hb has upstreamed into sof repo ? I can park this repo if ready now ?

**Comment by mengdonglin** [comment]
> @RanderWang @kv2019i should we be pushing PRs here now that @marc-hb has upstreamed into sof repo ? I can park this repo if ready now ?

@lgirdwood This is for making dummy smart amp loadable for mtl-006 only which is still using this separate rimage. This is not for SOF main branch where loadable module support is not available.

**Comment by pjdobrowolski** [comment]
You can load any loadable module on sof main only if it use standard native system service.

**Review by pjdobrowolski — APPROVED** [review]

**Review by marc-hb — CHANGES_REQUESTED** [review]
I think the SOF `mtl-006` branch should use a new `rimage` `mtl-006` branch, not the rimage main branch.

**Comment by mengdonglin** [comment]
> I think the SOF `mtl-006` branch should use a new `rimage` `mtl-006` branch, not the rimage main branch.

@marc-hb  The `rimage` `mtl-006` branch already exists for previous mtl-006 FW release. Current PR is for https://github.com/thesofproject/rimage/tree/mtl-006-drop-stable, not the main rimage branch of rimage.

**Pull request merged**
