### PR TITLE
Initial commit of rimage tool

### PR DESCRIPTION
**Pull request by dcpleung**
This is the initial commit to add the `rimage` tool. Zephyr is in the process of enabling a BSP for the APL DSP on UP Squared board, which requires rimage to build the firmware. Discussion with @lgirdwood resulted in this work. Note that the files under `src/include/sof/` are only needed when building without the SOF tree. If the SOF tree path is passed to `configure` with `--with-sof-source=<path>`, the same-name files in the SOF tree are used instead.

This utilizes autotool and thus the tool can be built with configure/make.

### CODE REVIEW

**Comment by dbaluta** [comment]
@dcpleung is there possible to also import the git history from old repo?

**Comment by dcpleung** [comment]
@dbaluta Let me try.

**Comment by cujomalainey** [comment]
Only ways I can think of doing that is either copying the whole history and deleting everything else or manually cherry-picking the history of the rimage folder and handling backports where necessary

**Comment by lgirdwood** [comment]
I dont think it's a big deal if history cannot be easily preserved here as it will still be in the main sof repo master branch.

**Comment by dcpleung** [comment]
Updated it with history of rimage (files under SOF's rimage/).

**Comment by cujomalainey** [comment]
I don't see the keys committed here, will they be passed in by the builders?

**Comment by dbaluta** [comment]
@dcpleung thanks for taking care of this! Looks good to me.

**Comment by dcpleung** [comment]
@cujomalainey The keys are still in the SOF repo, and will be passed as command line arguments.

**Comment by cujomalainey** [comment]
@dcpleung thanks :) what is the motivation for splitting this out of the SOF repo? I thought the reason for merging the SOFT repo was so we had less issues with keeping ABIs in sync across tools, this seems like a step backward since there are copies of the IPC ABI in these commits.

**Comment by dcpleung** [comment]
Zephyr is in the process of enabling a BSP for the APL DSP on UP Squared board, which requires rimage to build the firmware. Discussion with @lgirdwood resulted in this work. Note that the files under `src/include/sof/` are only needed when building without the SOF tree. If the SOF tree path is passed to `configure` with `--with-sof-source=<path>`, the same-name files in the SOF tree are used instead.

**Comment by cujomalainey** [comment]
Sounds good to me, thanks for the information

**Comment by plbossart** [comment]
> Zephyr is in the process of enabling a BSP for the APL DSP on UP Squared board, which requires rimage to build the firmware. Discussion with @lgirdwood resulted in this work. Note that the files under `src/include/sof/` are only needed when building without the SOF tree. If the SOF tree path is passed to `configure` with `--with-sof-source=<path>`, the same-name files in the SOF tree are used instead.

Please add this to the PR description...

my concern is that once you have rimage, you'll want to use actual code from the SOF tree, so what's the plan here? The last split and merge of SOFT was a nightmare, I'd like to make sure we have a direction that's well agreed on. Any solution that impacts our ability to bisect is a NAK.

**Comment by jajanusz** [comment]
Why was it merged? I see there a bit of mess. Fe. 2 buildsystems - automake and  cmake, we can go with just cmake as both sof and zephyr use it.

**Comment by plbossart** [comment]
> Why was it merged? I see there a bit of mess. Fe. 2 buildsystems - automake and cmake, we can go with just cmake as both sof and zephyr use it.

agree.

**Comment by lgirdwood** [comment]
I'm guessing this is an issue for Windows ?

Userspace tooling is traditionally built with autotools since it has no extra dependencies and easy for the distros. I've no objections to cmake if someone wants to copy the current camke file over.

**Comment by marc-hb** [comment]
Anyone looking for the rimage history and hitting the first, b537522 commit in this repo (a.k.a. the "end of the road") must continue to https://github.com/thesofproject/soft/commits/72d797d9ddae7 (and not to https://github.com/thesofproject/tools which is not a thing, thanks @ranj063 for the tip)

> Only ways I can think of doing that is either copying the whole history and deleting everything else or manually cherry-picking the history of the rimage folder and handling backports where necessary

I remember `git filter-branch` could do pretty much anything - including shooting in an unlimited number feet. Now I see `git help filter-branch` recommends `git filter-repo` instead, never tried the new one.

**Comment by marc-hb** [comment]
> Anyone looking for the rimage history [...] must continue to https://github.com/thesofproject/soft/commits/72d797d9ddae7

Funny enough I just discovered that this sof-tools.git history is also in sof.git thanks to @cujomalainey (thanks!)

Complete story at
- https://github.com/thesofproject/sof/issues/8178#issuecomment-1710615354

... where merging rimage back is discussed.

**Pull request merged**
