### PR TITLE
mtl: remove pin description from extended module config

### PR DESCRIPTION
**Pull request by yongzhi1**
Extended module config such as pin description is not used by driver, let's remove them, lest anyone waste time on the don't care values when adding a new module.

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@mwasko @marcinszkudlinski will this be needed in the future ?

**Comment by marcinszkudlinski** [comment]
We need at least number of pins for each module.
I would not remove it, 

now formats and pins are verified when pipeline starts (module_prepare), which may be a little too late. Bind IPC should not be accepted if connecting not compatible modules or not existing pins - based on info from the manifest.

So yes, those may become useful really soon.

**Comment by yongzhi1** [comment]
Thanks for the info, I somehow got the impression that Extended Manifest ("$AE1" ) is not used by FW.

**Comment by lgirdwood** [comment]
@yongzhi1 I will close this now. It can be re-opende later if direction changes.

**Pull request closed without merging**
