### PR TITLE
[TEST ONLY] Add RTC_AEC module

### PR DESCRIPTION
**Pull request by yongzhi1**

### CODE REVIEW

**Review by lgirdwood — COMMENTED** [review]
@yongzhi1 any CPC data for AEC ?

**Comment by lgirdwood** [comment]
@marcinszkudlinski do you need this for mtl-006 ?

**Comment by singalsu** [comment]
> @yongzhi1 Can you make this also for tgl and tgl-h, thanks!

No need, I just created #183

**Review by kv2019i — CHANGES_REQUESTED** [review]
@yongzhi1 Please resubmit directly to SOF repo if needed (rimage moved to sof/tools/rimage).

**Pull request closed without merging**
