### PR TITLE
kpb: update UUID

### PR DESCRIPTION
**Pull request by fkwasowi**
Change of uuid
regarding Windows compatibility

### CODE REVIEW

**Review by kv2019i — APPROVED** [review]

**Comment by kv2019i** [comment]
@aiChaoSONG This is good to go, we are not using kpb yet in MTL topologies, so I don't see this breaking anything.

**Review by pblaszko — APPROVED** [review]

**Comment by plbossart** [comment]
@kv2019i Don't we use KPB in the Wake-on-Voice cases? We have such implementations on TGL and ADL.

The rule of UUID is that they NEVER change....

**Comment by fkwasowi** [comment]
@plbossart Change does not affect TGL and ADL and IPC3 topology

**Comment by plbossart** [comment]
@fkwasowi what makes you say that?

````
m4/kpbm.m4:dnl Define macro for Key Phrase Buffer Manager(kpbm) widget
m4/kpbm.m4:DECLARE_SOF_RT_UUID("kpb", kpb_uuid, 0xd8218443, 0x5ff3, 0x4a4c,
m4/kpbm.m4:`            SOF_TKN_COMP_UUID'              STR(kpb_uuid)
sof-adl-nau8825.m4:# PCM100 <---- kpb <---- DMIC16K (dmic 16k capture)
sof-tgl-max98357a-rt5682.m4:# PCM100 <---- kpb <---- DMIC16K (dmic 16k capture)
sof-tgl-max98373-rt5682.m4:# PCM100 <---- kpb <---- DMIC16K (dmic 16k capture)
sof-tgl-sdw-max98373-rt5682.m4:# PCM12 <---- kpb <---- DMIC16k  (dmic 16k capture)
sof/pipe-kfbm-capture.m4:include(`kpbm.m4')
sof/pipe-kfbm-capture.m4:# kpbm initial parameters, aligned with struct sof_kpb_config
sof/pipe-kfbm-no-lp-capture.m4:include(`kpbm.m4')
sof/pipe-kfbm-no-lp-capture.m4:# kpbm initial parameters, aligned with struct sof_kpb_config
sof/pipe-vol-kfbm-capture.m4:include(`kpbm.m4')
sof/pipe-vol-kfbm-capture.m4:# kpbm initial parameters, aligned with struct sof_kpb_config
````

I see multiple TGL/ADL topologies using this UUID.

Please prove me wrong.

**Comment by plbossart** [comment]
and the worry is on the IMX side, not sure if @dbaluta can confirm if the KPB component is used by NXP.

**Comment by pblaszko** [comment]
> @fkwasowi what makes you say that?

@plbossart we totally agree UUID should be unchanged, but this is an exception - requirement to support Windows OED (transparent change from OED POV) was added on later phase of SOF project. UUID for KPB was defined in closed-source long time before SOF was initiated. Now we need to compatibility.

By not affecting ADL and TGL, @fkwasowi meant this change is done only for MTL IPC4 builds. Older projects keep old UUID for KPB.

**Comment by plbossart** [comment]
I appreciate the explanation @pblaszko. There's still a risk that someone might try to test a MTL topology on TGL IPC4, which is still the primary test vehicle as of today.

**Pull request merged**
