### PR TITLE
rimage signing support for CAVS2.5

### PR DESCRIPTION
**Pull request by lgirdwood**
This PR will add signing support for CAVS2.5 platforms. Key differences are hashes are now SHA384 and signing is now RSA PSS. This is a plan B until meu can be released.

TODO:

- [x] CSE checksum is 32bits instead of 8bits and needs fixed. Unsure of checksum end address (i.e. scope of data that is checksummed).
- [x] Hashes start/end and sizes for ext0x16 and ext signed_pkg
- [x] Validation support to be added to rimage - this allows the tool to self validate and to validate meu (as a means to confirming CAVS2.5 signing is correct as PSS signatures are not reproducible)

### CODE REVIEW

**Comment by lgirdwood** [comment]
@lyakh @juimonen @harshapriya-n @mwasko @cujomalainey @singalsu fyi
@juimonen can you take a look at the CSE checksum - I will do the other two.

**Comment by lgirdwood** [comment]
@juimonen btw, a quick way to visualise any delta can be done using meld after stripping ext manifest and converting to text. i.e.
```
./scripts/xtensa-build-all.sh tgl
dd if=build_tgl_gcc/sof-tgl.ri bs=1 skip=784 of=sof-tgl.ri-strip
hexdump -C sof-tgl.ri-strip > sof-tgl.ri.txt
```
You will also need to force rimage signing in xtensa-build-all for tgl

**Comment by juimonen** [comment]
@lgirdwood it seems that meu is calculating crc32 checksum...

**Comment by juimonen** [comment]
@lgirdwood FYI: https://github.com/juimonen/rimage/tree/crc32

**Comment by lgirdwood** [comment]
@juimonen can you check if we need any changes to SOF build scripts to use rimage for TGL. Thanks

**Comment by juimonen** [comment]
@lgirdwood yes we need this: https://github.com/thesofproject/sof/pull/3604

**Comment by lgirdwood** [comment]
CI showing checkpatch warnings.

**Pull request merged**
